authors/urls.py
from django.urls import path
from rest_framework.routers import SimpleRouter

from . import views

app_name = "authors"

author_api_router = SimpleRouter()
author_api_router.register("api", views.AuthorViewSet, basename="author-api")

urlpatterns = [
    path(
        "register/",
        views.register_view,
        name="register",
    ),
    path(
        "register/create/",
        views.register_create,
        name="register_create",
    ),
    path("login/", views.login_view, name="login"),
    path(
        "login/create/",
        views.login_create,
        name="login_create",
    ),
    path(
        "logout/",
        views.logout_view,
        name="logout",
    ),
    path(
        "dashboard/",
        views.dashboard_view,
        name="dashboard",
    ),
    path(
        "dashboard/",
        views.dashboard_view,
        name="dashboard",
    ),
    path(
        "dashboard/recipe/new/",
        views.DashboardRecipe.as_view(),
        name="dashboard_recipe_new",
    ),
    path(
        "dashboard/recipe/delete/",
        views.DashboardRecipeDelete.as_view(),
        name="dashboard_recipe_delete",
    ),
    path(
        "dashboard/recipe/<int:id>/edit/",
        views.DashboardRecipe.as_view(),
        name="dashboard_recipe_edit",
    ),
    path(
        "profile/<int:id>/",
        views.ProfileView.as_view(),
        name="profile",
    ),
]


urlpatterns += author_api_router.urls

recipes/urls.py
from django.urls import include, path
from rest_framework.routers import SimpleRouter
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
    TokenVerifyView,
)

from recipes import views

app_name = "recipes"

recipe_api_v2_router = SimpleRouter()
recipe_api_v2_router.register("", views.RecipeAPIV2ViewSet, basename="recipes-api")


urlpatterns = [
    path("recipes/api/token/", TokenObtainPairView.as_view(), name="token_obtain_pair"),
    path(
        "recipes/api/token/refresh/", TokenRefreshView.as_view(), name="token_refresh"
    ),
    path("recipes/api/token/verify/", TokenVerifyView.as_view(), name="token_verify"),
    path(
        "",
        views.RecipeListViewHome.as_view(),
        name="home",
    ),
    path(
        "recipes/category/<int:category_id>/",
        views.RecipeListViewCategory.as_view(),
        name="category",
    ),
    path(
        "recipes/<int:pk>/",
        views.RecipeDetail.as_view(),
        name="recipe",
    ),
    path("recipes/search/", views.RecipeListViewSearch.as_view(), name="search"),  # type: ignore
    # API
    path(
        "recipes/api/v1", views.RecipeListViewHomeAPI.as_view(), name="recipes_api_v1"
    ),
    path(
        "recipes/api/v1/<int:pk>",
        views.RecipeDetailAPI.as_view(),
        name="recipes_detail_api_v1",
    ),
    path("recipes/api/v2/", include(recipe_api_v2_router.urls)),
    # path(
    #     "recipes/api/v2/",
    #     views.RecipeAPIV2ViewSet.as_view(
    #         {
    #             "get": "list",
    #             "post": "create",
    #         }
    #     ),
    #     name="recipe_api_v2_list",
    # ),
    # path(
    #     "recipes/api/v2/<int:pk>",
    #     views.RecipeAPIV2ViewSet.as_view(
    #         {
    #             "get": "retrieve",
    #             "patch": "partial_update",
    #             "delete": "destroy",
    #         }
    #     ),
    #     name="recipe_api_v2_detail",
    # ),
]

recipes/views.py
from django.http import Http404
from django.http.response import HttpResponse as HttpResponse
from .models import Recipe
from django.db.models import Q

from django.http import JsonResponse
from django.utils import translation
from django.utils.translation import gettext as _
from utils.pagination import make_pagination
from django.forms.models import model_to_dict
import os
from django.views.generic import (
    ListView,
    DetailView,
)

PER_PAGE = int(os.environ.get("PER_PAGE", 6))


class RecipeListViewBase(ListView):
    model = Recipe
    context_object_name = "recipes"
    ordering = ["-id"]
    template_name = "recipes/pages/home.html"

    def get_queryset(self, *args, **kwargs):
        query_set = super().get_queryset(*args, **kwargs)
        query_set = query_set.filter(
            is_published=True,
        )
        query_set = query_set.select_related(
            "category", "author__profile"
        )  # use this to n+1 queries
        # query_set = query_set.prefetch_related("category")  # use this to n+n queries
        return query_set

    def get_context_data(self, *args, **kwargs):
        ctx = super().get_context_data(*args, **kwargs)
        page_obj, pagination_range = make_pagination(
            self.request,
            ctx.get("recipes"),
            PER_PAGE,
        )
        html_language = translation.get_language()

        ctx.update(
            {
                "recipes": page_obj,
                "pagination_range": pagination_range,
                "html_language": html_language,
            }
        )
        return ctx


class RecipeListViewHome(RecipeListViewBase):
    template_name = "recipes/pages/home.html"


class RecipeListViewHomeAPI(RecipeListViewBase):
    template_name = "recipes/pages/home-api.html"

    def render_to_response(self, context, **response_kwargs):
        recipes_dict = self.get_context_data()["recipes"]
        recipes_list = recipes_dict.object_list.values()
        return JsonResponse(list(recipes_list), safe=False)


class RecipeListViewCategory(RecipeListViewBase):
    template_name = "recipes/pages/category.html"

    def get_context_data(self, *args, **kwargs):
        category_translation = _("Category")
        ctx = super().get_context_data(*args, **kwargs)

        ctx.update({"title": f'{ctx.get("recipes")[0].category.name} - Category | {category_translation}'})  # type: ignore

        return ctx

    def get_queryset(self, *args, **kwargs):
        query_set = super().get_queryset(*args, **kwargs)
        query_set = query_set.filter(category__id=self.kwargs.get("category_id"))

        if not query_set.exists():
            raise Http404()

        return query_set


class RecipeListViewSearch(RecipeListViewBase):
    template_name = "recipes/pages/search.html"

    def get_queryset(self, *args, **kwargs):
        search_term = self.request.GET.get("q", "").strip()
        query_set = super().get_queryset(*args, **kwargs)

        if not search_term:
            raise Http404()

        """
        Isso é equivalente a:
        Buscar em Recipe, campos que tenham is_published = True e dentro dessa regra:

        buscar em Recipe o campo title que contenha search_term 
        OU 
        buscar em Recipe o campo description que contenha search_term

        o Q é um objeto que permite a criação de queries complexas
        """
        query_set = query_set.filter(
            Q(
                Q(title__icontains=search_term) | Q(description__icontains=search_term),
            ),
            is_published=True,
        )

        return query_set

    def get_context_data(self, *args, **kwargs):
        ctx = super().get_context_data(*args, **kwargs)
        search_term = self.request.GET.get("q", "").strip()
        page_obj, pagination_range = make_pagination(
            self.request,
            ctx.get("recipes"),
            PER_PAGE,
        )
        ctx.update(
            {
                "page_title": f'Search for "{search_term}"',
                "search_term": search_term,
                "additional_url_query": f"&q={search_term}",
                "recipes": page_obj,
                "pagination_range": pagination_range,
            }
        )
        return ctx


class RecipeDetail(DetailView):
    model = Recipe
    context_object_name = "recipe"
    template_name = "recipes/pages/recipe-view.html"

    def get_queryset(self, *args, **kwargs):
        query_set = super().get_queryset(*args, **kwargs)
        query_set = query_set.filter(
            is_published=True,
        )
        return query_set

    def get_context_data(self, *args, **kwargs):
        ctx = super().get_context_data(*args, **kwargs)

        ctx.update(
            {
                "is_detail_page": True,
            }
        )

        return ctx


class RecipeDetailAPI(RecipeDetail):
    def render_to_response(self, context, **response_kwargs):
        recipe = self.get_context_data()["recipe"]
        recipe_dict = model_to_dict(recipe)

        if recipe_dict.get("cover"):
            recipe_dict["cover"] = (
                self.request.build_absolute_uri() + recipe_dict["cover"].url
            )

        del recipe_dict[
            "is_published"
        ]  # Se eu não quiser que o campo is_published seja retornado

        return JsonResponse(recipe_dict, safe=False)

recipes/views/api.py
from django.shortcuts import get_object_or_404
from rest_framework import request, response, status
from rest_framework.pagination import PageNumberPagination
from rest_framework.permissions import IsAuthenticatedOrReadOnly
from rest_framework.viewsets import ModelViewSet

from recipes.permissions import IsOwner

from ..models import Recipe
from ..serializers import RecipeSerializer


class RecipeAPIv2Pagination(PageNumberPagination):
    page_size = 2


class RecipeAPIV2ViewSet(ModelViewSet):
    queryset = Recipe.objects.get_published()  # type: ignore
    serializer_class = RecipeSerializer
    pagination_class = RecipeAPIv2Pagination
    permission_classes = [
        IsAuthenticatedOrReadOnly,
    ]
    http_method_names = ["get", "post", "patch", "head", "delete"]

    def create(self, request: request.Request, *args, **kwargs):
        serializer = self.get_serializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        serializer.save(author=request.user)
        headers = self.get_success_headers(serializer.data)
        return response.Response(
            serializer.data, status=status.HTTP_201_CREATED, headers=headers
        )

    def get_queryset(self):
        qs = super().get_queryset()

        category_id = self.request.query_params.get("category_id", "")  # type: ignore

        if category_id != "" and category_id.isnumeric():
            qs = qs.filter(category_id=category_id)

        return qs

    def get_object(self, *args, **kwargs):
        pk = self.kwargs.get("pk", "")
        recipe = get_object_or_404(self.get_queryset(), pk=pk)

        self.check_object_permissions(self.request, recipe)

        return recipe

    def get_permissions(self):
        if self.request.method in ["PATCH", "DELETE"]:
            return [
                IsOwner(),
            ]
        return super().get_permissions()

    def partial_update(self, request: request.Request, *args, **kwargs):
        recipe = self.get_object()

        serializer = RecipeSerializer(
            instance=recipe,
            data=request.data,
            partial=True,
            many=False,
            context={"request": request},
        )
        serializer.is_valid(raise_exception=True)
        serializer.save()
        return response.Response(serializer.data)


# class RecipeAPIv2ListCreate(ListCreateAPIView):
#     queryset = Recipe.objects.get_published()  # type: ignore
#     serializer_class = RecipeSerializer
#     pagination_class = RecipeAPIv2Pagination

# def get(self, request: Request):
#     recipes = Recipe.objects.get_published()[:10]  # type: ignore
#     # Sempre que for retornar mais de um objeto, é necessário passar o many=True
#     serializer = RecipeSerializer(instance=recipes, many=True)
#     return Response(serializer.data)

# def post(self, request):
#     data = request.data
#     serializer = RecipeSerializer(data=data)

#     serializer.is_valid(raise_exception=True)
#     serializer.save()

#     # return Response(serializer.validated_data, status=HTTPStatus.CREATED) # isso é bom para ver as validações
#     return Response(serializer.data, status=HTTPStatus.CREATED)


# class RecipeAPIv2DetailUpdateDelete(RetrieveUpdateDestroyAPIView):
#     queryset = Recipe.objects.get_published()  # type: ignore
#     serializer_class = RecipeSerializer
#     pagination_class = RecipeAPIv2Pagination

# def get(self, request: Request, pk: int):
#     recipe = get_object_or_404(Recipe, pk=pk, is_published=True)
#     serializer = RecipeSerializer(instance=recipe, many=False)
#     return Response(serializer.data)

# Caso eu queira sobrescrever o método update

# def delete(self, request: Request, pk: int):
#     recipe = get_object_or_404(Recipe, pk=pk, is_published=True)
#     recipe.delete()
#     return Response(status=HTTPStatus.NO_CONTENT)

recipes/views/site.py
import os

from django.db.models import Q
from django.forms.models import model_to_dict
from django.http import Http404, JsonResponse
from django.http.response import HttpResponse as HttpResponse
from django.views.generic import (
    DetailView,
    ListView,
)

from utils.pagination import make_pagination

from ..models import Recipe

PER_PAGE = int(os.environ.get("PER_PAGE", 6))


class RecipeListViewBase(ListView):
    model = Recipe
    context_object_name = "recipes"
    ordering = ["-id"]
    template_name = "recipes/pages/home.html"

    def get_queryset(self, *args, **kwargs):
        query_set = super().get_queryset(*args, **kwargs)
        query_set = query_set.filter(
            is_published=True,
        )
        query_set = query_set.select_related(
            "category", "author__profile"
        )  # use this to n+1 queries
        # query_set = query_set.prefetch_related("category")  # use this to n+n queries
        return query_set

    def get_context_data(self, *args, **kwargs):
        ctx = super().get_context_data(*args, **kwargs)
        page_obj, pagination_range = make_pagination(
            self.request,
            ctx.get("recipes"),
            PER_PAGE,
        )
        ctx.update(
            {
                "recipes": page_obj,
                "pagination_range": pagination_range,
            }
        )
        return ctx


class RecipeListViewHome(RecipeListViewBase):
    template_name = "recipes/pages/home.html"


class RecipeListViewHomeAPI(RecipeListViewBase):
    template_name = "recipes/pages/home-api.html"

    def render_to_response(self, context, **response_kwargs):
        recipes_dict = self.get_context_data()["recipes"]
        recipes_list = recipes_dict.object_list.values()
        return JsonResponse(list(recipes_list), safe=False)


class RecipeListViewCategory(RecipeListViewBase):
    template_name = "recipes/pages/category.html"

    def get_context_data(self, *args, **kwargs):
        ctx = super().get_context_data(*args, **kwargs)

        ctx.update({"title": f"{ctx.get('recipes')[0].category.name} - Category | "})  # type: ignore

        return ctx

    def get_queryset(self, *args, **kwargs):
        query_set = super().get_queryset(*args, **kwargs)
        query_set = query_set.filter(category__id=self.kwargs.get("category_id"))

        if not query_set.exists():
            raise Http404()

        return query_set


class RecipeListViewSearch(RecipeListViewBase):
    template_name = "recipes/pages/search.html"

    def get_queryset(self, *args, **kwargs):
        search_term = self.request.GET.get("q", "").strip()
        query_set = super().get_queryset(*args, **kwargs)

        if not search_term:
            raise Http404()

        """
        Isso é equivalente a:
        Buscar em Recipe, campos que tenham is_published = True e dentro dessa regra:

        buscar em Recipe o campo title que contenha search_term
        OU
        buscar em Recipe o campo description que contenha search_term

        o Q é um objeto que permite a criação de queries complexas
        """
        query_set = query_set.filter(
            Q(
                Q(title__icontains=search_term) | Q(description__icontains=search_term),
            ),
            is_published=True,
        )

        return query_set

    def get_context_data(self, *args, **kwargs):
        ctx = super().get_context_data(*args, **kwargs)
        search_term = self.request.GET.get("q", "").strip()
        page_obj, pagination_range = make_pagination(
            self.request,
            ctx.get("recipes"),
            PER_PAGE,
        )
        ctx.update(
            {
                "page_title": f'Search for "{search_term}"',
                "search_term": search_term,
                "additional_url_query": f"&q={search_term}",
                "recipes": page_obj,
                "pagination_range": pagination_range,
            }
        )
        return ctx


class RecipeDetail(DetailView):
    model = Recipe
    context_object_name = "recipe"
    template_name = "recipes/pages/recipe-view.html"

    def get_queryset(self, *args, **kwargs):
        query_set = super().get_queryset(*args, **kwargs)
        query_set = query_set.filter(
            is_published=True,
        )
        return query_set

    def get_context_data(self, *args, **kwargs):
        ctx = super().get_context_data(*args, **kwargs)

        ctx.update(
            {
                "is_detail_page": True,
            }
        )

        return ctx


class RecipeDetailAPI(RecipeDetail):
    def render_to_response(self, context, **response_kwargs):
        recipe = self.get_context_data()["recipe"]
        recipe_dict = model_to_dict(recipe)

        if recipe_dict.get("cover"):
            recipe_dict["cover"] = (
                self.request.build_absolute_uri() + recipe_dict["cover"].url
            )

        del recipe_dict[
            "is_published"
        ]  # Se eu não quiser que o campo is_published seja retornado

        return JsonResponse(recipe_dict, safe=False)

recipes/templates/recipes/partials/head.html
{% load static %} <!-- Carrega os arquivos estaticos -->

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css"
        integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/brands.min.css"
        integrity="sha512-8RxmFOVaKQe/xtg6lbscU9DU0IRhURWEuiI0tXevv+lXbAHfkpamD4VKFQRto9WgfOJDwOZ74c/s9Yesv3VvIQ=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/solid.min.css"
        integrity="sha512-pZlKGs7nEqF4zoG0egeK167l6yovsuL8ap30d07kA5AJUq+WysFlQ02DLXAmN3n0+H3JVz5ni8SJZnrOaYXWBA=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'recipes/css/styles.css' %}">

recipes/templates/recipes/partials/recipe.html
<div class="recipe recipe-list-item">
    {% if recipe.cover %}
        <div class="recipe-cover">
            <a href="{{ recipe.get_absolute_url }}">
                <img src="{{ recipe.cover.url }}" alt="Temporário">
            </a>
        </div>
    {% endif %}
    <div class="recipe-title-container">
        <h2 class="recipe-title">
            <a href="{{ recipe.get_absolute_url }}">
                {{ recipe.title }}
            </a>
        </h2>
    </div>

    <div class="recipe-author">

        {% if recipe.author is not None %}
            <span class="recipe-author-item">

                {% if recipe.author.profile %}
                    <a href="{% url 'authors:profile' recipe.author.profile.id %}">
                {% endif %}

                <i class="fas fa-user"></i>
                {% if recipe.author.first_name %}
                    {{ recipe.author.first_name }} {{ recipe.author.last_name }}
                {% else %}
                    {{ recipe.author.username }}
                {% endif %}

                {% if recipe.author.profile %}
                    </a>
                {% endif %}

            </span>
        {% endif %}

        <span class="recipe-author-item">
            <i class="fas fa-calendar-alt"></i>
            {{ recipe.created_at|date:"d/m/Y" }} às {{ recipe.created_at|date:"H:i" }}
        </span>

        {% if recipe.category is not None %}
            <span class="recipe-author-item">
                <a href="{% url 'recipes:category' recipe.category.id %}">
                    <i class="fas fa-layer-group"></i>
                    <span>{{ recipe.category.name }}</span>
                </a>
            </span>
        {% endif %}
    </div>

    <div class="recipe-content">
        <p>{{ recipe.description }}</p>
    </div>

    <div class="recipe-meta-container">
        <div class="recipe-meta recipe-preparation">
            <h3 class="recipe-meta-title"><i class="fas fa-stopwatch"></i> Preparo</h3>
            <div class="recipe-meta-text">
                {{ recipe.preparation_time }} {{ recipe.preparation_time_unit }}
            </div>
        </div>
        <div class="recipe-meta recipe-servings">
            <h3 class="recipe-meta-title"><i class="fas fa-pizza-slice"></i> Porções</h3>
            <div class="recipe-meta-text">
                {{ recipe.servings }} {{ recipe.servings_unit }}
            </div>
        </div>
    </div>

    {% if is_detail_page is not True %}
        <footer class="recipe-footer">
            <a class="recipe-read-more button button-dark button-full-width" href="{% url 'recipes:recipe' recipe.id %}">
                <i class="fas fa-eye"></i>
                <span>ver mais...</span>
            </a>
        </footer>
    {% endif %}

    {% if is_detail_page is True %}
        <div class="preparation-steps">
            {% if recipe.preparation_steps_is_html is True %}
                {{ recipe.preparation_steps|safe }}
            {% else %}
                {{ recipe.preparation_steps|linebreaksbr }}
            {% endif %}
        </div>
    {% endif %}

</div>